In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

### Creating an Array

In [2]:
# Creating Numpy Arrays
mylist = [1,2,3,4]

In [3]:
my_array = np.array(mylist)

In [4]:
mylist2 =[11,22,33,44]

In [5]:
mylists = [mylist, mylist2]

In [6]:
myArrays = np.array(mylists)

In [7]:
myArrays

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
myArrays.shape

(2, 4)

In [9]:
myArrays.dtype

dtype('int64')

In [10]:
zeroesArray = np.zeros(5)

In [11]:
zeroesArray

array([0., 0., 0., 0., 0.])

In [13]:
onesArray = np.ones([5,5])

In [14]:
emptyArray = np.empty(5)

In [15]:
identityMatrix = np.eye(5)

In [16]:
rangeArray = np.arange(0,5,2)

In [17]:
rangeArray

array([0, 2, 4])

### Arrays and Scalars

In [18]:
5/2

2.5

In [20]:
arr1 = np.array([[1,2,3], [6,7,8]])

In [21]:
arr1

array([[1, 2, 3],
       [6, 7, 8]])

In [22]:
# I can matrix operations such as
arr1 * arr1

array([[ 1,  4,  9],
       [36, 49, 64]])

In [23]:
arr1 + arr1

array([[ 2,  4,  6],
       [12, 14, 16]])

In [24]:
arr1 / arr1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# I can carry out scalar operations
14 * arr1

array([[ 14,  28,  42],
       [ 84,  98, 112]])

In [27]:
1/arr1

array([[1.        , 0.5       , 0.33333333],
       [0.16666667, 0.14285714, 0.125     ]])

In [28]:
arr1 ** 3

array([[  1,   8,  27],
       [216, 343, 512]])

### Indexing Arrays

In [29]:
arr2 = np.arange(0,11)

In [31]:
arr2[1:5]

array([1, 2, 3, 4])

In [32]:
arr2[0:5] = 100

In [33]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
# Enables me to make a copy of an array
arr_copy = arr2.copy()

In [41]:
# indexing 3D Matrixes
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [42]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr_2d[2][2]

9

In [48]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [49]:
# fancy indexing
arr_2d2 = np.zeros((10,10))

In [50]:
arr_length = arr_2d2.shape[1]

In [52]:
for i in range(arr_length):
    arr_2d2[i]=i

In [53]:
arr_2d2

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [54]:
arr_2d2[[2,4,6]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [59]:
# order doenst matter with fancy indexing:
arr_2d2[[6,3,4,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

### Transposition of Matrices

In [60]:
arr_t = np.arange(50).reshape((10,5))

In [62]:
arr_t.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [66]:
np.dot(arr_t.T, arr_t)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

### Universal Array Functions

In [67]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# Sqrt
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [69]:
# Exponential of an array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
# binary functions
A = np.random.randn(10)

In [71]:
A

array([ 0.51745409, -0.18621147, -0.2920551 , -0.07096064, -0.79283976,
        2.23857239,  1.10199313,  1.71215803, -0.99546984,  0.30363258])

In [72]:
B = np.random.randn(10)

In [73]:
np.add(A,B)

array([-1.11618799, -0.77391733, -1.26719779,  1.39854107,  0.07994471,
        3.79072914,  1.22732998,  1.46549725, -1.24858845,  2.0908802 ])

In [74]:
np.maximum(A,B)

array([ 0.51745409, -0.18621147, -0.2920551 ,  1.4695017 ,  0.87278447,
        2.23857239,  1.10199313,  1.71215803, -0.25311861,  1.78724762])