In [3]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# filtering arrays with where clauses
A = np.array([12,34,5])

In [11]:
B = np.array([100,200,300])

In [15]:
condition = np.array([True, True,False])

In [16]:
answer = [(A_val if cond else B_val) for A_val, B_val, cond in zip(A,B,condition)]

In [9]:
answer

[12, 34, 300]

In [17]:
answer2 = np.where(condition,A,B)

In [18]:
answer2

array([ 12,  34, 300])

In [22]:
answer2.sum(0)

346

In [23]:
answer2.mean()

115.33333333333333

In [24]:
answer2.var()

17131.55555555556

In [25]:
answer2.std()

130.88756837666273

In [26]:
bool_array = np.array([True,False,True])

In [27]:
bool_array.any()

True

In [28]:
bool_array.all()

False

In [40]:
arr = np.random.randn(5)

In [41]:
arr

array([ 0.06088449, -0.2734768 ,  0.19219621, -2.03201885, -0.74075992])

In [42]:
arr.sort()

In [43]:
arr

array([-2.03201885, -0.74075992, -0.2734768 ,  0.06088449,  0.19219621])

In [46]:
countries = np.array(["France", "Germany", "Russia", "Germany", "Brazil"])

In [47]:
countries

array(['France', 'Germany', 'Russia', 'Germany', 'Brazil'], dtype='<U7')

In [48]:
np.unique(countries)

array(['Brazil', 'France', 'Germany', 'Russia'], dtype='<U7')

In [50]:
# check to see if values exists in a 1dimensional array
np.in1d(["Germany", "Sweden"],countries)

array([ True, False])

### Storing data into an array

In [51]:
arr = np.arange(5)

In [52]:
arr

array([0, 1, 2, 3, 4])

In [53]:
np.save("my_array",arr)

In [54]:
arr14 = np.load("my_array.npy")

In [57]:
np.savez("myZip.npz", x=arr,y=arr14)

In [58]:
arraysZipped = np.load("myZip.npz")

In [59]:
arraysZipped['x']

array([0, 1, 2, 3, 4])

In [61]:
arraysZipped['y']

array([0, 1, 2, 3, 4])